# 01 - Exploratory Data Analysis

Objetivo:
Analizar la estructura de los datos, identificar valores nulos,
comprobar la frecuencia temporal y estudiar la calidad de la información.

# 1.1. Carga de datos

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Entorno preparado correctamente")

Entorno preparado correctamente

# 1.2. Inspección inicial y análisis de valores nulos

In [2]:
gen1 = pd.read_csv("../data/Plant_1_Generation_Data.csv")

gen1.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,15-05-2020 00:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0
1,15-05-2020 00:00,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0
2,15-05-2020 00:00,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0
3,15-05-2020 00:00,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0
4,15-05-2020 00:00,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0

In [3]:
gen1.info()

<class 'pandas.DataFrame'>
RangeIndex: 68778 entries, 0 to 68777
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE_TIME    68778 non-null  str
 1   PLANT_ID     68778 non-null  int64
 2   SOURCE_KEY   68778 non-null  str
 3   DC_POWER     68778 non-null  float64
 4   AC_POWER     68778 non-null  float64
 5   DAILY_YIELD  68778 non-null  float64
 6   TOTAL_YIELD  68778 non-null  float64
dtypes: float64(4), int64(1), str(2)
memory usage: 3.7 MB

In [4]:
gen1.describe()

        PLANT_ID      DC_POWER      AC_POWER   DAILY_YIELD   TOTAL_YIELD
count    68778.0  68778.000000  68778.000000  68778.000000  6.877800e+04
mean   4135001.0   3147.426211    307.802752   3295.968737  6.978712e+06
std          0.0   4036.457169    394.396439   3145.178309  4.162720e+05
min    4135001.0      0.000000      0.000000      0.000000  6.183645e+06
25%    4135001.0      0.000000      0.000000      0.000000  6.512003e+06
50%    4135001.0    429.000000     41.493750   2658.714286  7.146685e+06
75%    4135001.0   6366.964286    623.618750   6274.000000  7.268706e+06
max    4135001.0  14471.125000   1410.950000   9163.000000  7.846821e+06

In [5]:
gen1["SOURCE_KEY"].nunique()

22

In [6]:
gen1.isnull().sum()

DATE_TIME      0
PLANT_ID       0
SOURCE_KEY     0
DC_POWER       0
AC_POWER       0
DAILY_YIELD    0
TOTAL_YIELD    0
dtype: int64

In [7]:
weather1 = pd.read_csv("../data/Plant_1_Weather_Sensor_Data.csv")

weather1.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
1,2020-05-15 00:15:00,4135001,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0
2,2020-05-15 00:30:00,4135001,HmiyD2TTLFNqkNe,24.935753,22.592306,0.0
3,2020-05-15 00:45:00,4135001,HmiyD2TTLFNqkNe,24.846130,22.360852,0.0
4,2020-05-15 01:00:00,4135001,HmiyD2TTLFNqkNe,24.621525,22.165423,0.0

In [8]:
weather1.info()

<class 'pandas.DataFrame'>
RangeIndex: 3182 entries, 0 to 3181
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   DATE_TIME            3182 non-null   str
 1   PLANT_ID             3182 non-null   int64
 2   SOURCE_KEY           3182 non-null   str
 3   AMBIENT_TEMPERATURE  3182 non-null   float64
 4   MODULE_TEMPERATURE   3182 non-null   float64
 5   IRRADIATION          3182 non-null   float64
dtypes: float64(3), int64(1), str(2)
memory usage: 149.3 KB

In [9]:
weather1.isnull().sum()

DATE_TIME              0
PLANT_ID               0
SOURCE_KEY             0
AMBIENT_TEMPERATURE    0
MODULE_TEMPERATURE     0
IRRADIATION            0
dtype: int64

# 1.3. Análisis temporal

In [10]:
gen1["DATE_TIME"] = pd.to_datetime(gen1["DATE_TIME"])

weather1["DATE_TIME"] = pd.to_datetime(weather1["DATE_TIME"])

C:\Users\maksy\AppData\Local\Temp\ipykernel_17904\2836205876.py:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  gen1["DATE_TIME"] = pd.to_datetime(gen1["DATE_TIME"])

In [11]:
gen1["DATE_TIME"].sort_values().head(10)

0    2020-05-15
20   2020-05-15
19   2020-05-15
18   2020-05-15
17   2020-05-15
16   2020-05-15
14   2020-05-15
13   2020-05-15
12   2020-05-15
11   2020-05-15
Name: DATE_TIME, dtype: datetime64[us]

In [12]:
gen1["DATE_TIME"].sort_values().tail(10)

68763   2020-06-17 23:45:00
68762   2020-06-17 23:45:00
68760   2020-06-17 23:45:00
68759   2020-06-17 23:45:00
68758   2020-06-17 23:45:00
68757   2020-06-17 23:45:00
68756   2020-06-17 23:45:00
68776   2020-06-17 23:45:00
68765   2020-06-17 23:45:00
68777   2020-06-17 23:45:00
Name: DATE_TIME, dtype: datetime64[us]

In [13]:
gen1["DATE_TIME"].nunique()

3158

In [14]:
weather1["DATE_TIME"].nunique()

3182

In [15]:
gen1["DATE_TIME"].drop_duplicates().sort_values().head(20)

0     2020-05-15 00:00:00
21    2020-05-15 00:15:00
42    2020-05-15 00:30:00
63    2020-05-15 00:45:00
84    2020-05-15 01:00:00
106   2020-05-15 01:15:00
127   2020-05-15 01:30:00
148   2020-05-15 01:45:00
170   2020-05-15 02:00:00
191   2020-05-15 02:15:00
212   2020-05-15 02:30:00
233   2020-05-15 02:45:00
254   2020-05-15 03:00:00
275   2020-05-15 03:15:00
296   2020-05-15 03:30:00
317   2020-05-15 03:45:00
338   2020-05-15 04:00:00
359   2020-05-15 04:15:00
381   2020-05-15 04:30:00
403   2020-05-15 04:45:00
Name: DATE_TIME, dtype: datetime64[us]

In [16]:
weather1["DATE_TIME"].drop_duplicates().sort_values().head(20)

0    2020-05-15 00:00:00
1    2020-05-15 00:15:00
2    2020-05-15 00:30:00
3    2020-05-15 00:45:00
4    2020-05-15 01:00:00
5    2020-05-15 01:15:00
6    2020-05-15 01:30:00
7    2020-05-15 01:45:00
8    2020-05-15 02:00:00
9    2020-05-15 02:15:00
10   2020-05-15 02:30:00
11   2020-05-15 02:45:00
12   2020-05-15 03:00:00
13   2020-05-15 03:15:00
14   2020-05-15 03:30:00
15   2020-05-15 03:45:00
16   2020-05-15 04:00:00
17   2020-05-15 04:15:00
18   2020-05-15 04:30:00
19   2020-05-15 04:45:00
Name: DATE_TIME, dtype: datetime64[us]

# 1.4. Análisis de inversores

In [19]:
gen1.groupby("DATE_TIME")["SOURCE_KEY"].count().describe()

count    3158.000000
mean       21.778974
std         1.475566
min         4.000000
25%        22.000000
50%        22.000000
75%        22.000000
max        22.000000
Name: SOURCE_KEY, dtype: float64

In [20]:
gen1.groupby("DATE_TIME")["SOURCE_KEY"].count().value_counts()

SOURCE_KEY
22    3057
10      32
21      27
14      23
18      14
4        2
20       1
16       1
19       1
Name: count, dtype: int64

In [21]:
gen1["PLANT_ID"].unique()

array([4135001])

In [22]:
weather1["PLANT_ID"].unique()

array([4135001])